name = "HospitalScheduling"
uuid = "12345678-1234-1234-1234-1234567890ab"
authors = ["Antigravity"]
version = "0.1.0"

[deps]
JuMP = "4076af6c-e467-56ae-b986-b466b27495ed"
HiGHS = "87dc4568-4c63-4d18-bc4d-4ba9acc386f1"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1.6"
JuMP = "1.0"
HiGHS = "1.0"
DataFrames = "1.0"
CSV = "0.10"
